export const VIEWER_NEXT_ENGINE_CONTRACT_VERSION = "0.2.2";

export const viewerNextEngineContract = Object.freeze({
  version: VIEWER_NEXT_ENGINE_CONTRACT_VERSION,
  sourceTypes: Object.freeze(["Uint8Array", "ArrayBuffer", "{ data }"]),
  methods: Object.freeze([
    "addImage",
    "addBookmarkFromSelection",
    "clearHistory",
    "deleteBookmark",
    "destroy",
    "download",
    "exportData",
    "exportRedacted",
    "find",
    "fitPageWidth",
    "getState",
    "goToHistoryDestination",
    "goToBookmark",
    "goToPage",
    "deleteSavedSignature",
    "listSavedSignatures",
    "nextPage",
    "openSignatureDialog",
    "organizePages",
    "previousPage",
    "print",
    "readInteractionStateAtPoint",
    "resetZoom",
    "redo",
    "resetSelectedEditorRotation",
    "rotateSelectedEditorClockwise",
    "rotateClockwise",
    "save",
    "setDrawStyle",
    "setDrawTool",
    "setFreeTextStyle",
    "setHighlightColor",
    "setNativeRedactMode",
    "setNativeTextEditMode",
    "setScale",
    "setStampSelection",
    "setTool",
    "startSelectedEditorResize",
    "undo",
    "updateBookmarkTitle",
    "useSavedSignature",
    "zoomIn",
    "zoomOut",
    "zoomWithWheel",
  ]),
  stateKeys: Object.freeze([
    "activeTool",
    "bookmarks",
    "capabilities",
    "error",
    "find",
    "freeTextFonts",
    "freeTextStyle",
    "highlightColor",
    "loading",
    "nativeEditing",
    "pageNumber",
    "pagePdfSize",
    "pagesCount",
    "pageSize",
    "pageSizes",
    "rotation",
    "scale",
    "scalePercent",
    "scaleValue",
    "viewerInteractionState",
  ]),
  viewerInteractionState: Object.freeze({
    capabilities: Object.freeze([
      "canBookmark",
      "canComment",
      "canDelete",
      "canHighlight",
      "canRedact",
      "canResetRotation",
      "canResize",
      "canRotate",
      "canStyle",
      "canTransform",
      "canUseContextMenu",
    ]),
    selectionKinds: Object.freeze([
      "none",
      "text",
      "annotation-editor",
      "native-text",
      "redaction",
    ]),
    contextTargetKinds: Object.freeze([
      "text",
      "freetext",
      "highlight",
      "ink",
      "image",
      "stamp",
      "signature",
      "native-text",
      "redaction",
    ]),
  }),
  assetStrategy: Object.freeze({
    cMaps:
      "viewer-next build copies pdf.js cMaps to build/generic/viewer-next/pdfjs/cmaps/",
    css: "viewer-next imports shared viewer CSS from src/display/pdf_viewer.css",
    standardFonts:
      "viewer-next build copies standard fonts to build/generic/viewer-next/pdfjs/standard_fonts/",
    wasm: "viewer-next build copies pdf.js WASM assets to build/generic/viewer-next/pdfjs/wasm/",
    worker: "pdfDocumentLoader derives pdf.worker.mjs from import.meta.url",
  }),
});
